name: HealthBook
description: A new Flutter project. Created by Slidy

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

## Slidy Scripts 
vars: 
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner
scripts: 
    mobx_build: $runner build
    mobx_watch: $clean & $get & $runner watch
    mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs



environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_mobx: ^1.1.0+2
  flutter_svg: ^0.19.1
  mobx: ^1.2.1+4
  flutter_modular: ^2.0.1
  auto_size_text: ^2.1.0
  smooth_page_indicator: ^0.2.0
  image_picker: ^0.6.6+1
  modal_progress_hud: ^0.1.3
  provider: ^4.3.2+2
  brasil_fields: ^0.4.0
  shared_preferences: ^0.5.12
  bubble_tab_indicator: ^0.1.4
  intl: ^0.16.1
  table_calendar: ^2.3.1
  validators: ^2.0.1
  file_picker: ^2.1.5+1
  cpf_cnpj_validator: ^1.0.5
  flutter_facebook_login: ^3.0.0
  ff_navigation_bar: ^0.1.5
  font_awesome_flutter: ^8.10.0
  material_design_icons_flutter: ^4.0.5855
  menu_button: ^1.2.1
  syncfusion_flutter_sliders: ^18.4.35-beta
  tridimensional_drawer: ^0.1.1
  flux_validator_dart: ^1.0.3
  path_provider: ^1.6.24
  dotted_border: ^1.0.6
  google_sign_in: ^4.5.4
  http: ^0.12.2
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  mockito: ^4.1.4
  modular_codegen:
  mobx_codegen: ^1.1.2
  build_runner: ^1.10.1
  change_app_package_name: ^0.1.2
  local_auth: ^0.6.3+2
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/logos/
    - assets/images/icons/


  fonts:
    - family: Montserrat Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.otf
    - family: Montserrat Light
      fonts:
        - asset: assets/fonts/Montserrat-Light.otf
    - family: Montserrat Medium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.otf
    - family: Montserrat Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
    - family: Montserrat SemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.otf
    - family: OpenSans Regular
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: NavigationIcons
      fonts:
        - asset: assets/images/custom/NavigationIcons.ttf
    - family: JunkIcon
      fonts:
        - asset: assets/images/custom/JunkIcon.ttf
    - family: NewIcons
      fonts:
        - asset: assets/images/custom/NewIcons.ttf